package com.eastcom.social.pos.core.orm.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table POLICY_DOCUMENT.
 */
public class PolicyDocument {

    private String id;
    private String createDate;
    private String updateDate;
    private String name;
    private String versionCode;
    private String fileNo;
    private String publishDate;
    private String isPublishing;
    private String publishStatusLbl;

    public PolicyDocument() {
    }

    public PolicyDocument(String id) {
        this.id = id;
    }

    public PolicyDocument(String id, String createDate, String updateDate, String name, String versionCode, String fileNo, String publishDate, String isPublishing, String publishStatusLbl) {
        this.id = id;
        this.createDate = createDate;
        this.updateDate = updateDate;
        this.name = name;
        this.versionCode = versionCode;
        this.fileNo = fileNo;
        this.publishDate = publishDate;
        this.isPublishing = isPublishing;
        this.publishStatusLbl = publishStatusLbl;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode;
    }

    public String getFileNo() {
        return fileNo;
    }

    public void setFileNo(String fileNo) {
        this.fileNo = fileNo;
    }

    public String getPublishDate() {
        return publishDate;
    }

    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate;
    }

    public String getIsPublishing() {
        return isPublishing;
    }

    public void setIsPublishing(String isPublishing) {
        this.isPublishing = isPublishing;
    }

    public String getPublishStatusLbl() {
        return publishStatusLbl;
    }

    public void setPublishStatusLbl(String publishStatusLbl) {
        this.publishStatusLbl = publishStatusLbl;
    }

}
