package com.eastcom.social.pos.core.orm.entity;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEMP_BLACK_LIST.
 */
public class TempBlackList {

    private String SocialCardNo;
    private java.util.Date Time;

    public TempBlackList() {
    }

    public TempBlackList(String SocialCardNo) {
        this.SocialCardNo = SocialCardNo;
    }

    public TempBlackList(String SocialCardNo, java.util.Date Time) {
        this.SocialCardNo = SocialCardNo;
        this.Time = Time;
    }

    public String getSocialCardNo() {
        return SocialCardNo;
    }

    public void setSocialCardNo(String SocialCardNo) {
        this.SocialCardNo = SocialCardNo;
    }

    public java.util.Date getTime() {
        return Time;
    }

    public void setTime(java.util.Date Time) {
        this.Time = Time;
    }

}
