package com.eastcom.social.pos.core.orm.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.eastcom.social.pos.core.orm.entity.UnknowMedicine;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table UNKNOW_MEDICINE.
*/
public class UnknowMedicineDao extends AbstractDao<UnknowMedicine, String> {

    public static final String TABLENAME = "UNKNOW_MEDICINE";

    /**
     * Properties of entity UnknowMedicine.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property BarCode = new Property(0, String.class, "barCode", true, "BAR_CODE");
    };


    public UnknowMedicineDao(DaoConfig config) {
        super(config);
    }
    
    public UnknowMedicineDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'UNKNOW_MEDICINE' (" + //
                "'BAR_CODE' TEXT PRIMARY KEY NOT NULL );"); // 0: barCode
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'UNKNOW_MEDICINE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UnknowMedicine entity) {
        stmt.clearBindings();
 
        String barCode = entity.getBarCode();
        if (barCode != null) {
            stmt.bindString(1, barCode);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UnknowMedicine readEntity(Cursor cursor, int offset) {
        UnknowMedicine entity = new UnknowMedicine( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // barCode
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UnknowMedicine entity, int offset) {
        entity.setBarCode(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(UnknowMedicine entity, long rowId) {
        return entity.getBarCode();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(UnknowMedicine entity) {
        if(entity != null) {
            return entity.getBarCode();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
